# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoBingo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoBingo
  
  pod 'RxSwift', git: 'https://github.com/ReactiveX/RxSwift.git', branch: 'rxswift4.0-swift4.0'
  pod 'RxCocoa', git: 'https://github.com/ReactiveX/RxSwift.git', branch: 'rxswift4.0-swift4.0'
  pod 'RxDataSources', git: 'https://github.com/RxSwiftCommunity/RxDataSources.git', branch: 'swift4.0'
  pod 'Action', git: 'https://github.com/RxSwiftCommunity/Action.git', branch: 'master'
  pod 'RxGesture'
  pod 'NeoCoordinator'
  pod 'RxCoordinator'
  pod 'Reusable'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'SwinjectAutoregistration'

end
