# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoBingo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoBingo
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'Action'
  pod 'NeoCoordinator'
  pod 'RxCoordinator'
  pod 'Reusable'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'SwinjectAutoregistration'

end
